/**
 * Generated by `pnpm boneyard:build` (dev server must be running).
 * Empty registry is valid — `<Skeleton>` falls back to `fallback` UI until bones exist.
 */
import { registerBones } from "boneyard-js/react"

registerBones({})
