const COUNTRY_FLAGS: Record<string, string> = {
  "United States": "🇺🇸",
  Canada: "🇨🇦",
  "United Kingdom": "🇬🇧",
  Germany: "🇩🇪",
  France: "🇫🇷",
  Italy: "🇮🇹",
  Spain: "🇪🇸",
  Netherlands: "🇳🇱",
  Australia: "🇦🇺",
  Japan: "🇯🇵",
  China: "🇨🇳",
  India: "🇮🇳",
  Brazil: "🇧🇷",
  Mexico: "🇲🇽",
  Argentina: "🇦🇷",
  "South Korea": "🇰🇷",
  Russia: "🇷🇺",
  Turkey: "🇹🇷",
  "Saudi Arabia": "🇸🇦",
  "South Africa": "🇿🇦",
  Nigeria: "🇳🇬",
  Egypt: "🇪🇬",
  Morocco: "🇲🇦",
  Kenya: "🇰🇪",
  Ghana: "🇬🇭",
  Thailand: "🇹🇭",
  Vietnam: "🇻🇳",
  Singapore: "🇸🇬",
  Malaysia: "🇲🇾",
  Indonesia: "🇮🇩",
  Philippines: "🇵🇭",
  Pakistan: "🇵🇰",
  Bangladesh: "🇧🇩",
  "Sri Lanka": "🇱🇰",
  UAE: "🇦🇪",
  Israel: "🇮🇱",
  Poland: "🇵🇱",
  "Czech Republic": "🇨🇿",
  Hungary: "🇭🇺",
  Romania: "🇷🇴",
  Bulgaria: "🇧🇬",
  Croatia: "🇭🇷",
  Serbia: "🇷🇸",
  Ukraine: "🇺🇦",
  Belarus: "🇧🇾",
  Lithuania: "🇱🇹",
  Latvia: "🇱🇻",
  Estonia: "🇪🇪",
  Finland: "🇫🇮",
  Sweden: "🇸🇪",
  Norway: "🇳🇴",
  Denmark: "🇩🇰",
  Iceland: "🇮🇸",
  Ireland: "🇮🇪",
  Portugal: "🇵🇹",
  Switzerland: "🇨🇭",
  Austria: "🇦🇹",
  Belgium: "🇧🇪",
  Luxembourg: "🇱🇺",
  Greece: "🇬🇷",
  Cyprus: "🇨🇾",
  Malta: "🇲🇹",
  "New Zealand": "🇳🇿",
  Chile: "🇨🇱",
  Peru: "🇵🇪",
  Colombia: "🇨🇴",
  Venezuela: "🇻🇪",
  Ecuador: "🇪🇨",
  Bolivia: "🇧🇴",
  Paraguay: "🇵🇾",
  Uruguay: "🇺🇾",
  "Costa Rica": "🇨🇷",
  Panama: "🇵🇦",
  Guatemala: "🇬🇹",
  Honduras: "🇭🇳",
  "El Salvador": "🇸🇻",
  Nicaragua: "🇳🇮",
  Belize: "🇧🇿",
  Jamaica: "🇯🇲",
  Cuba: "🇨🇺",
  "Dominican Republic": "🇩🇴",
  Haiti: "🇭🇹",
  "Puerto Rico": "🇵🇷",
  "Trinidad and Tobago": "🇹🇹",
  Barbados: "🇧🇧",
  Bahamas: "🇧🇸",
}

export function getCountryFlag(countryName: string): string {
  return COUNTRY_FLAGS[countryName] ?? "🌍"
}
