ALTER TABLE "website_audit"
  ADD COLUMN IF NOT EXISTS "progress_current" VARCHAR(500),
  ADD COLUMN IF NOT EXISTS "progress_done" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "progress_total" INTEGER NOT NULL DEFAULT 0;
